% Create videos from images in given folder
close all
clear all
clc

selector = 'QUALITY'
type = 'original' % 'FeatureSelection'
videoPath = '.'
%videoPath = '/media/luca/DATAPART1/resultsStereoVIO/result-2017-06-21-testXXX-comparison-100-10-noBetween-minDist4-noSuccProg-QUALITY200-VIDEO'
imagesInputPaths = {horzcat(videoPath,'/result-',type,'-MH_01_easy-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-MH_02_easy-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-MH_03_medium-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-MH_04_difficult-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-MH_05_difficult-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-V1_01_easy-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-V1_02_medium-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-V1_03_difficult-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-V2_01_easy-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-V2_02_medium-',selector,'/'),...
    horzcat(videoPath,'/result-',type,'-V2_03_difficult-',selector,'/')};

% Create a video for each folder:
for i=1:length(imagesInputPaths)
    if strcmp(type,'original')==1
        fps = 10;
        str = 'original-';
    else
        fps = 10;
        str = '';
    end
    videoOutputFilename = horzcat('./','result-video-',str,num2str(i));
    createVideoFromImages(imagesInputPaths{i},'img_%d.png#',videoOutputFilename,fps)
end

% imagesInputPaths = {'./result-original-MH_01_easy-QUALITY/','./result-original-MH_02_easy-QUALITY/','./result-original-MH_03_medium-QUALITY/',...
%     './result-original-MH_04_difficult-QUALITY/','./result-original-MH_05_difficult-QUALITY/','./result-original-V1_01_easy-QUALITY/',...
%     './result-original-V1_02_medium-QUALITY/','./result-original-V1_03_difficult-QUALITY/','./result-original-V2_01_easy-QUALITY/',...
%     './result-original-V2_02_medium-QUALITY/','./result-original-V2_03_difficult-QUALITY/',...
%     './result-original-killian_01-QUALITY/','./result-original-killian_02-QUALITY/',...
%     './result-original-killian_03-QUALITY/','./result-original-B36_01-QUALITY/',...
%     './result-original-B38_01-QUALITY/','./result-original-eastman_01-QUALITY/'};
% 
% % Create a video for each folder:
% for i=12:16 % length(imagesInputPaths)
% fps = 20*0.2;
% videoOutputFilename = horzcat('./','video-original-',num2str(i));
% imagesInputPath = horzcat(imagesInputPaths{i});
% createVideoFromImages(imagesInputPath,'img_%d.png#',videoOutputFilename,fps)
% end

