rm \
addedFactors.eps \
addedFactors.fig \
featureSelectionTime.eps \
featureSelectionTime.fig \
imuBiases.eps \
imuBiases.fig \
imuPredictRelativeErrors.eps \
imuPredictRelativeErrors.fig \
imuRotPreintErrors.eps \
imuRotPreintErrors.fig \
keyframeSpacing.eps \
keyframeSpacing.fig \
monoErrors.eps \
monoErrors.fig \
nrKeysInState.eps \
nrKeysInState.fig \
nrTrackedFeatures.eps \
nrTrackedFeatures.fig \
output.txt \
output_landmarks.txt \
output_normals.txt \
output_posesGT.txt \
output_posesVIO.txt \
output_smartFactors.txt \
output_statsFactors.txt \
output_statsTracker.txt \
output_timingTracker.txt \
output_timingVIO.txt \
ransacStats.eps \
ransacStats.fig \
rpyErrors.eps \
rpyErrors.fig \
smartFactorsStats.eps \
smartFactorsStats.fig \
stereoErrors.eps \
stereoErrors.fig \
stereoTraslationConsistency.eps \
stereoTraslationConsistency.fig \
trackLengthStats.eps \
trackLengthStats.fig \
trackerParameters.txt \
trackerStats.eps \
trackerStats.fig \
trackerTiming.eps \
trackerTiming.fig \
velocityErrors.eps \
velocityErrors.fig \
vioErrors.eps \
vioErrors.fig \
vioErrorsAligned.eps \
vioErrorsAligned.fig \
vioParameters.txt \
vioRelativeErrors.eps \
vioRelativeErrors.fig \
vioTiming.eps \
vioTiming.fig \
vioTimingBreakdown.eps \
vioTimingBreakdown.fig \
vioTrajectoriesAligned.eps \
vioTrajectoriesAligned.fig \
