rm \
output_landmarks.txt \
output_mesh.ply \
output_normals.txt \
output_posesGT.csv \
output_posesGT.txt \
output_posesVIO.csv \
output_posesVIO.txt \
output_smartFactors.txt \
output_statsFactors.txt \
output_statsTracker.txt \
output_timingTracker.txt \
output_timingVIO.txt \
output.txt \
